carilogo/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('search.urls', namespace='search') )
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

search/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^$', SearchView.as_view(), name="index"),
]

search/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

search/forms.py
from django import forms

class SearchForm(forms.Form):
    image = forms.ImageField()

core/views.py
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings


class StaticRedirectView(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        return "%s%s" % (settings.STATIC_URL, self.request.path)


class AngularRedirectView(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        return "%s%s" % (settings.ANGULAR_URL, self.request.path)

search/views.py
import json
import cv2
import os
import csv

from weka.core import jvm
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
from django.conf import settings
from django.http import JsonResponse

from .forms import SearchForm
from lib.search.fba.searcher import Searcher
from lib.search.fba.preprocess import Preprocess
from lib.search import cluster
from lib.tools import make_sure_path_exists, handle_uploaded_file


class SearchView(FormView):
    form_class = SearchForm
    template_name = "search/index.html"

    def post(self, request, *args, **kwargs):
        # import pdb; pdb.set_trace()
        image_file = request.FILES['file']

        use_cedd = request.POST.get('use_cedd')
        # try:
        #     use_cedd = request.POST.get('use_cedd', 0))
        # except ValueError:
        #     use_cedd = 0

        if use_cedd:
            RAW_INDEX = "cedd_beverages.csv"
            CLUSTERED_MODEL = "cedd_clusterer.model"
            CLUSTERED_INDEX = "cedd_clustered.csv"
            IMAGE_FOLDER = "sorted"

            query = None
            with open(RAW_INDEX, 'r') as csvfile:
                readers = csv.reader(csvfile)
                for row in readers:
                    if image_file.name == row[-1]:
                        query = row
                        print "got the name"
                        break
            features = query[:-2]
            distance_method="braycurtis"
        else:
            CLUSTERED_MODEL = "sorted_kmeans.model"
            CLUSTERED_INDEX = "sorted_clustered.csv"
            IMAGE_FOLDER = "sorted"

            # create tmp_dir
            tmp_dir = os.path.join(settings.MEDIA_ROOT, 'tmp')
            make_sure_path_exists(tmp_dir)

            # save tmp file
            tmp_file = os.path.join(tmp_dir, 'tmp.jpg')
            # TODO: will become problem when multiuser access the same page
            handle_uploaded_file(image_file, tmp_file)

            # initialize the image descriptor
            cd = Preprocess((8, 8, 8))
            # load the query image and describe it
            query = cv2.imread(tmp_file)
            features = cd.describe(query)
            distance_method = "chi"

        print CLUSTERED_INDEX, CLUSTERED_MODEL
        searcher = Searcher(CLUSTERED_INDEX, use_cluster=True)
        cluster_group = cluster.query_instance(features, model=CLUSTERED_MODEL)
        seconds, images = searcher.search(
            features, distance_method=distance_method, cluster_group=cluster_group, limit=None)

        # if jvm.started:
        #     jvm.javabridge.detach()
        #     jvm.stop()
        result = {
            'seconds': seconds,
            'images': ["%s/%s/%s" % (settings.MEDIA_URL, IMAGE_FOLDER, image[1]) for image in images]
        }
        return JsonResponse(result, safe=False)

views.py
import json
from django.shortcuts import render
from django.views.generic import TemplateView, FormView

from .forms import SearchForm
from lib.search.fba.preprocess import Preprocess
from lib.search.fba.searcher import Searcher


class SearchView(TemplateView):
    template_name="search/index.html"

    def post(self, request, *args, **kwargs):
        image = self.request['file']
        return super(SearchView,self).post(request, *args, **kwargs)

search/templates/search/index.html
{% extends 'base.html' %} {% load staticfiles %} {% block main-body %}
<div id="top-menu">
    <div class="container">
        <div class="title-logo">
            <a href="" class="navbar-brand">
                <img src="{% static 'images/logo-web.svg' %}" alt="{{title}}"></a>
        </div>
        <form enctype="multipart/form-data" id="upload-file" action="{% url 'search:index' %}" method="post" class="dropzone">
            {% csrf_token %}
            <!-- <input type="hidden" value="1" name="use_cedd"> -->
            <!-- <div id="upload-file" class="form-group is-empty is-fileinput"> -->
            <!-- <input type="file" multiple="" id="inputFile3">
                <a class="btn btn-raised btn-danger" href="#"><i class="material-icons">file_upload</i> Upload sample gambar </a>
                <span class="material-input"></span></div> -->
            <div class="togglebutton">
              <label>
                CEDD
                <input type="checkbox" checked="1" name="use_cedd"><span class="toggle"></span>
              </label>
            </div>
        </form>
    </div>
</div>

<div id="gallery" class="container-fluid">
    <p class="seconds"></p>
    <div class="row">
        <div class="col-md-12"></div>
    </div>
</div>
{% endblock main-body %}


{% block extra-scripts %}
<script src="{% static 'bower_components/dropzone/dist/dropzone.js' %}" charset="utf-8"></script>

{% verbatim %}
<script id="image-template" type="text/x-handlebars-template">
  <div class="image-frame">
    <img class="img-responsive" src="{{ image_path }}" alt="" style="max-width:100px">
  </div>
</script>
{% endverbatim %}

<script>
    // add dropzone
    $(function() {
        'use strict';
        var source = $("#image-template").html();
        var template = Handlebars.compile(source);

        Dropzone.options.uploadFile = {
            parallelUploads: 100,
            paramName: 'file',
            maxFiles: 1,
            acceptedFiles: 'image/*',
            addRemoveLinks: true,
            success: function(event, response) {
                var res = response;
                console.log(res)
                $('#gallery .col-md-12').html('');
                $("#gallery .seconds").text(res.seconds + " detik")
                for (var i = 0; i < res.images.length; i++) {
                  var context = { image_path: res.images[i] };
                  var render = template(context);
                  $('#gallery .col-md-12').append(render);
                }
            },
            // error: function(file, errorMessage, xhr){
            //   alert(errorMessage);
            //   this.removeFile(file);
            // },
            // success: function(file){
            //   this.removeAllFiles();
            // }
        }
    });
</script>
{% endblock extra-scripts %}

templates/base.html
{% load staticfiles %}

<html>
<head>
  <title>Cari logo</title>
  <link rel="shortcut icon" href="{% static 'images/logo_ico.png' %}">
  <!-- Material Design fonts -->
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

  <!-- Bootstrap -->
  <link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">

  <!-- Bootstrap Material Design -->
  <link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap-material-design/dist/css/bootstrap-material-design.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap-material-design/dist/css/ripples.min.css' %}">
  <link rel="stylesheet" href=" {% static 'stylesheets/screen.css' %}">
  <!-- Custom styles -->
  <link rel="stylesheet" href="">
  {% block extra-styles %}{% endblock extra-styles %}
</head>
<body>
  {% block main-body %}{% endblock main-body %}

  <script src="{% static 'bower_components/jquery/dist/jquery.js' %}" charset="utf-8"></script>
  <script src="{% static 'bower_components/bootstrap-material-design/dist/js/material.js' %}" charset="utf-8"></script>
  <script src="{% static 'bower_components/bootstrap-material-design/dist/js/ripples.js' %}" charset="utf-8"></script>
  <script src="{% static 'bower_components/handlebars/handlebars.js'%}" charset="utf-8"></script>
  <script>
      // using jQuery
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie != '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) == (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
  </script>
  {% block extra-scripts %}{% endblock extra-scripts %}
</body>
</html>